### ISSUE TITLE
consider advertising it on invidio.us

### ISSUE THREAD

**Issue by elypter** [omarroth/archive#10]
i don't know if this much attention is needed or wanted but jan 15th seems very close to me. is there any way to see the progress?

**Comment by omarroth** [comment]
You can see progress [here](https://archive.omar.yt/api/stats). I've already advertised it elsewhere, but I will absolutely consider advertising it on the site depending on how much attention it gets.

**Comment by elypter** [comment]
interesting. are there only 45800*10000 videos on youtube? i would have assume its a lot more

**Comment by elypter** [comment]
is the crawling done by this application too?

**Comment by elypter** [comment]
maybe something like this helps to find the videos that are not linked to anything https://www.randomlyinspired.com/noviews

**Comment by hofmand** [comment]
Also see https://the-eye.eu/public/Random/yt-metadata-archive/channelcrawler.com_part1.txt for a (partial) list of channel IDs.

**Comment by omarroth** [comment]
Since the project is now mostly completed, I'm going to close this.
