### ISSUE TITLE
Everything completed?

### ISSUE THREAD

**Issue by elypter** [omarroth/archive#13]
It appears that everything has been backed up now. CONGRATULATIONS! the script also doesnt upload anything anymore. wouldnt it be beneficial to still recieve uploads for possible error corrections or are there possibly other sources for video ids? especially since there are now so many active workers.

**Comment by omarroth** [comment]
Please do stick around! I'm currently pulling video IDs from playlists and already archived annotation data, which can both contain unlisted videos that I would like to have archived, and I expect to keep adding more content until the 15th.

Currently, all workers should be verifying data that has already been uploaded. If there are any problems verifying, then we'll need workers to help pull down any data.

For the most part though this is the final stretch! Thank you and everyone else contributing to this project.

**Comment by omarroth** [comment]
I updated the README with a notice indicating this project is mostly completed. At this point everything is being sorted through and uploaded to the Internet Archive.

Again, thank you and everyone for helping to save a massive part of internet history.
