### ISSUE TITLE
Invalid size error

### ISSUE THREAD

**Issue by elypter** [omarroth/archive#14]
i am getting invalid size errors all the time now

Continuing 57f8b4c2-16c9-4ef1-899f-f4063cf75054...
GC Warning: Repeated allocation of very large block (appr. size 33558528):
	May lead to memory leak and poor performance
All annotations collected (39.5 MiB)    
Compressing...
Committing...
Invalid size for 57f8b4c2-16c9-4ef1-899f-f4063cf75054
Continuing 57f8b4c2-16c9-4ef1-899f-f4063cf75054...
GC Warning: Repeated allocation of very large block (appr. size 67112960):
	May lead to memory leak and poor performance
All annotations collected (39.5 MiB)    
Compressing...
Committing...
Invalid size for 57f8b4c2-16c9-4ef1-899f-f4063cf75054
Continuing 57f8b4c2-16c9-4ef1-899f-f4063cf75054...
GC Warning: Repeated allocation of very large block (appr. size 67112960):
	May lead to memory leak and poor performance
All annotations collected (39.5 MiB)    
Compressing...
Committing...
Invalid size for 57f8b4c2-16c9-4ef1-899f-f4063cf75054

**Comment by omarroth** [comment]
This was mentioned in the Discord as well:
>w.r.t. batches being rejected: the issue is likely annotations which disappear after a set amount of time, so "x user is livestreaming right now" can end up changing the size of the batch significantly if it contains multiple videos from the same channel

You can look at these two pastes side-by-side to see an example:
- https://cadence.gq/pastes/102
- https://cadence.gq/pastes/103

The first one has a `"teaser_text": "Litoral TV is live now!"`annotation that bumps the size of the single file significantly, multiplied by several videos by the same channel with the same additional annotation, can cause the batch to fail.

I plan on updating the server to accept batches in a wider range, so the one you submitted will be accepted. You may also need to clear the `config.json` (or remove .worker_info if you're using the Crystal worker) to get a new worker_id.

**Comment by omarroth** [comment]
> Just pushed a fix so workers will be able to submit a new version if they're well trusted
> This is in addition to the current batch, anything that has already been archived will not be overridden

So big changes in file sizes can be accepted. 44ddb17946cce99de2c53669e51ce8106f84af65 allows new versions to be uploaded, which I think closes this issue.

**Comment by skyfloogle** [comment]
The problem with that is that workers have to build reputation first. Otherwise, they get stuck on an infinite loop of invalid size errors without being assigned a new batch and become useless. This has happened to one of mine (batch fe9e101b-1040-4147-b592-bdc2fb8cfef2, 
[here's the batch.json.gz if that helps](https://github.com/omarroth/archive/files/2753591/batch.json.gz)).
