### ISSUE TITLE
failed to upload

### ISSUE THREAD

**Issue by elypter** [omarroth/archive#5]
uaing the crystal version i got this error:

GC Warning: Repeated allocation of very large block (appr. size 33558528):
	May lead to memory leak and poor performance
All annotations collected (28.1 MiB)    
Compressing...
Committing...
All annotations compressed (2.6 MiB)    
Uploading to S3...
Unhandled exception: Status 204 should not have a body (ArgumentError)
  from /usr/share/crystal/src/http/client/response.cr:0:11 in 'exec_internal_single'
  from /usr/share/crystal/src/http/client.cr:499:5 in 'exec'
  from /usr/share/crystal/src/http/client.cr:342:3 in 'post'
  from src/worker.cr:192:5 in '__crystal_main'
  from /usr/share/crystal/src/kernel.cr:453:5 in 'main'
  from /usr/share/crystal/src/string.cr:4202:5 in '__libc_start_main'
  from ???
niemand@akaralan:~/archive$

**Comment by omarroth** [comment]
Unfortunately I'm having trouble finding a solution to this, as it seems to be a bug in how Crystal handles 204 responses. The data is still successfully submitted, except the worker does not properly handle a success response.

As an ugly workaround, you can run it in a loop, like this:
```
$ while /bin/true; do ./worker -u https://archive.omar.yt -t 20; done
```

Although issues like these are why I'd recommend using the Node version of the worker in favor of this one.

**Comment by elypter** [comment]
thanks. you should add that to the readme as well. the node.js variant should be run in a while loop as well because there can always be a problem that makes it fail.
