### ISSUE TITLE
node.js variant exits if the batch finished but not all annotations were fetched

### ISSUE THREAD

**Issue by elypter** [omarroth/archive#7]
if i restart it continues with the last few missing ones. if it still cant download all of them i have to repeat again until it got all. then it uploads and starts a new batch.

**Comment by cloudrac3r** [comment]
Just pushed a fix to my fork. Use the new config.json setting `forceRetryAllErrors` (default: true) to make each annotation request retry all errors automatically.

**Comment by cloudrac3r** [comment]
I'll close the issue now, feel free to re-open if you have any more problems with the process exiting.
